name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd docker && docker build ./ --no-cache --build-arg GOLANG_VERSION=1.17.2 --build-arg DEFAULTNETWORK=datanet101 --tag go-algorand:${GITHUB_REF##*/}
